exec: ../dist/build/Greyhame/Greyhame
args:
    - production
host: greyha.me

# Use the following to automatically copy your bundle upon creation via `yesod
# keter`. Uses `scp` internally, so you can set it to a remote destination
copy-to: greyha.me:/opt/keter/incoming
