Default: &defaults
  host: "*4" # any IPv4 host
  port: 8080
  approot: "http://localhost:8080"
  copyright: All content released under the GNU Affero General Public License, version 3.
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  port: 80
  approot: "http://greyha.me"
  <<: *defaults
