Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright: All content copyright James H Fisher <jameshfisher@gmail.com> unless otherwise stated.
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  port: 80
  approot: "http://greyha.me"
  <<: *defaults
