Default: &defaults
  database: Greyhame.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Greyhame_test.sqlite3
  <<: *defaults

Staging:
  database: Greyhame_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: Greyhame_production.sqlite3
  poolsize: 100
  <<: *defaults
